[package]
name = "example-runner"
version = "0.1.0"
authors = ["Embark <opensource@embark-studios.com>"]
edition = "2018"

[dependencies]
winit = "0.19.5"
image = "0.10.4"
ash = "0.31"
ash-window = "0.5"

[build-dependencies]
spirv-builder = { path = "../../spirv-builder" }
