[package]
name = "rustc_codegen_spirv"
version = "0.1.0"
authors = ["Jasper Bekkers <bekkers@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["dylib"]

[dependencies]
rspirv = { git = "https://github.com/gfx-rs/rspirv" }

[dev-dependencies]
pretty_assertions = "0.6"
