[workspace]
members = [
    "examples/runners/cpu",
    "examples/runners/ash",
    "examples/runners/wgpu",
    "examples/shaders/sky-shader",
    "examples/shaders/simplest-shader",
    "rustc_codegen_spirv",
    "spirv-builder",
    "spirv-std",
    "spirv-tools",
    "spirv-tools-sys",
]

[patch.crates-io]
# https://github.com/bitshifter/glam-rs/pull/85
glam = { git = "https://github.com/EmbarkStudios/glam-rs", rev = "d55ff75e91aab01c4fd9808e3ca9c079dfa7315c" }
