[package]
name = "rspirv-linker"
version = "0.1.0"
authors = ["Jasper Bekkers <bekkers@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rspirv = { path = "C:/Users/Jasper/traverse/rspirv/rspirv/"}