[package]
name = "run_libcore_test"
version = "0.1.0"
authors = ["Ashley Hauck <ashley.hauck@embark-studios.com>"]
edition = "2018"

[dependencies]
ocl = { version = "", features = ["opencl_version_2_1"] }

[workspace]
